all: rtgen
rtgen:
	g++ ChainWalkContext.cpp ChainWalkSet.cpp CrackEngine.cpp Exception.cpp HashAlgorithm.cpp HashRoutine.cpp HashSet.cpp MemoryPool.cpp MySQL.cpp Public.cpp stdafx.cpp rsearch.cpp -I/usr/include/mysql -L/usr/lib/mysql -lmysqlclient -lssl -O3 -o rsearchi
